# Generated by Django 3.0.2 on 2020-07-25 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('toNotify', models.CharField(max_length=50)),
                ('due_date', models.DateTimeField()),
                ('rating', models.IntegerField()),
                ('completion_percentage', models.IntegerField(default=0)),
                ('compensation', models.IntegerField(default=0)),
                ('users_assigned', models.ManyToManyField(to='users.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('attended_users', models.ManyToManyField(to='users.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='DailyProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('progress_text', models.TextField()),
                ('image', models.ImageField(default='default.jpg', upload_to='Progress_Images')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.ToDoTask')),
            ],
        ),
    ]
